services:
  kali:
    build:
      context: kali/
    image: kali:${KALI_VERSION}
    hostname: kali

  snort:
    build:
      context: snort/
    image: snort:${SNORT_VERSION}
    hostname: snort

  tomcat:
    build:
      context: tomcat/
    image: tomcat:${TOMCAT_VERSION}

  caldera:
    build:
      context: caldera/
    image: caldera:${CALDERA_VERSION}

  vuln_apache:
    build:
      context: vuln_apache/
    image: vuln_apache:${VULN_APACHE_VERSION}
  
  metasploitable:
    build:
      context: metasploitable/
    image: metasploitable:${METASPLOITABLE_VERSION}
